  spring:
    datasource:
      #四要素
      username: root
      password: 12316
      url: jdbc:mysql:///thedate?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 自定义数据源
      type: com.alibaba.druid.pool.DruidDataSource
  mybatis:
    type-aliases-package: top.link666.thedate.pojo
    mapper-locations: classpath:mapper/*.xml
